# Generated by Django 4.1.7 on 2023-02-22 12:46

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ign', models.CharField(max_length=200, verbose_name='In-Game Name')),
                ('url', models.URLField(validators=[django.core.validators.URLValidator()])),
                ('rank', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Guess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('guess', models.CharField(max_length=20)),
                ('is_correct', models.BooleanField()),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='guesser.video')),
            ],
        ),
    ]
